//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellarBotHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beer
    {
        public Beer()
        {
            this.CellarEntries = new HashSet<CellarEntry>();
        }
    
        public int id { get; set; }
        public int brewery_id { get; set; }
        public string name { get; set; }
        public int cat_id { get; set; }
        public int style_id { get; set; }
        public Nullable<float> abv { get; set; }
        public string imagepath { get; set; }
        public string description { get; set; }
        public Nullable<long> upc { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string user_id { get; set; }
        public Nullable<bool> is_retired { get; set; }
    
        public virtual Brewery Brewery { get; set; }
        public virtual Category Category { get; set; }
        public virtual Style Style { get; set; }
        public virtual ICollection<CellarEntry> CellarEntries { get; set; }
    }
}
