//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellarBotHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beer
    {
        public int id { get; set; }
        public int brewery_id { get; set; }
        public string name { get; set; }
        public int cat_id { get; set; }
        public int style_id { get; set; }
        public float abv { get; set; }
        public float ibu { get; set; }
        public float srm { get; set; }
        public int upc { get; set; }
        public string filepath { get; set; }
        public string description { get; set; }
        public int add_user { get; set; }
        public System.DateTime last_mod { get; set; }
    }
}
