//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellarBotHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Beers = new HashSet<Beer>();
            this.Styles = new HashSet<Style>();
        }
    
        public int id { get; set; }
        public string cat_name { get; set; }
        public Nullable<System.DateTime> last_mod { get; set; }
    
        public virtual ICollection<Beer> Beers { get; set; }
        public virtual ICollection<Style> Styles { get; set; }
    }
}
