//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellarBotHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Style
    {
        public int id { get; set; }
        public int cat_id { get; set; }
        public string style_name { get; set; }
        public System.DateTime last_mod { get; set; }
    }
}
