//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellarBotHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Style
    {
        public Style()
        {
            this.Beers = new HashSet<Beer>();
        }
    
        public int id { get; set; }
        public int cat_id { get; set; }
        public string style_name { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    
        public virtual ICollection<Beer> Beers { get; set; }
        public virtual Category Category { get; set; }
    }
}
